"use client"

import { useSiteSettings } from './context/SiteSettingsContext';
import { useState, useEffect } from "react";
import localFont from "next/font/local";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});

const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export default function LayoutClient({ children }) {
    const { siteSettings, isLoading } = useSiteSettings();
    const [title, setTitle] = useState("Lumina Blue");

    useEffect(() => {
        if (siteSettings?.name) {
            setTitle(siteSettings.name);
        }
    }, [siteSettings]);

    return (
        <html lang="en">
            <head>
                <title>{isLoading ? "Loading..." : title}</title>
                <meta name="description" content="Generated by create next app" />
                <link
                    rel="icon"
                    type="image/png"
                    href={
                        siteSettings?.logo_light ||
                        siteSettings?.about?.logo_light
                    }
                />
            </head>

            <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen w-full`}>
                <main className="flex-grow w-full relative">
                    {children}
                </main>
            </body>
        </html>
    );
}
